# Generated by Django 5.2 on 2025-04-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_cash_onlinemoney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinemoney',
            name='client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
        migrations.AddField(
            model_name='client',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='online_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Cash',
        ),
        migrations.DeleteModel(
            name='OnlineMoney',
        ),
    ]
